### ISSUE TITLE
Erro ao adicionar a extensão no chrome

### ISSUE THREAD

**Issue by julianasm** [pablomuro/sigaa-unb-volta-horario#1]
Ao tentar adicionar a extensão ao chrome encontro esse erro:

Package is invalid. Details: 'Could not load icon './icons/unb_sigaa_16px.png' specified in 'icons'.'. 

Queria muito poder usar! Se puder resolver esse problema serei muito grata kkk

**Comment by pablomuro** [comment]
Opa, vou ver isso essa semana
Vlw por reportar

**Comment by pablomuro** [comment]
@julianasm , arrumei os trem lá eu acho - tem q esperar o google liberar 
mas tem como usar já

https://github.com/pablomuro/sigaa-unb-volta-horario#pra-quem-n%C3%A3o-conseguir-instalar-por-algum-motivo
