### ISSUE TITLE
Falta de conversão na tela de matricula

### ISSUE THREAD

**Issue by luisgfmarques** [pablomuro/sigaa-unb-volta-horario#3]
A extensão não funcionou na matricula das disciplinas

![Screenshot from 2021-01-04 20-55-36](https://user-images.githubusercontent.com/49294754/103594779-68051c80-4ed8-11eb-9870-d68b0f684f6a.png)

**Comment by pablomuro** [comment]
acabei de resolver isso, vou da update na chrome store agora
